NumPy Ndarray
--------------
Ndarray is the n-dimensional array object defined in the numpy which stores the collection of the similar type of elements. In other words, we can define a ndarray as the collection of the data type (dtype) objects.

The ndarray object can be accessed by using the 0 based indexing. Each element of the Array object contains the same size in the memory.

In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a= np.array([1,2.5,3])
print(a)

[1.  2.5 3. ]


In [4]:
a= np.array([1,2.5,'a'])
print(a)

['1' '2.5' 'a']


In [6]:
# string ----- upcasting
# float
# int

In [7]:
# more than one dimension
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [8]:
a=np.array([1,2,3,4,5],ndmin=2)
print(a)

[[1 2 3 4 5]]


In [9]:
a=np.array([1,2,3,4,5],ndmin=5)
print(a)

[[[[[1 2 3 4 5]]]]]


In [13]:
# dtype parameter ---- to change any data type
a=np.array([1,2,3],dtype=complex) # a+jb
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [12]:
# dtype parameter
a=np.array([1.0,2.0,3.0],dtype=int) 
print(a)

[1 2 3]


In [14]:
# ndarray.shape --- this attribute returns a tuple consisting of array dimension. It can also be used to resize the array.
a=np.array([[1,2,3],[4,5,6]])
print(a)
print()
print(a.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)


In [15]:
# this resizes the ndarray
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
# NumPy also provides a reshape function to resize an array.
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
# np.zeros() --- returns a new array of specified size and type, filled with zeros.

x=np.zeros((5))
print(x) # by default gives float

[0. 0. 0. 0. 0.]


In [20]:
x=np.zeros((5),dtype=int)
print(x)

[0 0 0 0 0]


In [23]:
x=np.zeros([2,2],dtype=int)
print(x)

[[0 0]
 [0 0]]


In [21]:
# np.ones --- returns a new array of specified size and type, filled with ones.

x=np.ones((5),dtype=int)
print(x)

[1 1 1 1 1]


In [22]:
x=np.ones([2,2],dtype=int)
print(x)

[[1 1]
 [1 1]]


In [25]:
# ndim --- to check dimension
a=np.zeros(5,dtype=int)
print(a)

[0 0 0 0 0]


In [26]:
a.ndim

1

In [27]:
a.shape

(5,)

In [28]:
a.size # length/ no of elements

5

In [29]:
x=2*(np.ones(5))
print(x)

[2. 2. 2. 2. 2.]


In [30]:
a=np.eye(5) # identity matrix
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
x1=np.array([[12,23,34],[45,56,67],[67,78,89]])
print(x1)

[[12 23 34]
 [45 56 67]
 [67 78 89]]


In [35]:
y=np.diag(x)# gives diagonal element
print(y)

[12 56 89]


In [36]:
x2=np.diag([4,5,6,7,8,9])
print(x2)

[[4 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 6 0 0 0]
 [0 0 0 7 0 0]
 [0 0 0 0 8 0]
 [0 0 0 0 0 9]]


In [37]:
# numpy.asarray ---
# This function is similar to numpy.array except for the fact that it has fewer parameters.
# this routine is useful for converting Python seq into array

In [38]:
x=[1,2,3,4]
print(type(x))
a=np.asarray(x)
print(type(a))
print(a)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4]


In [2]:
import numpy as np
x=[1,2,3]
a=np.asarray(x,dtype=float)
print(a)

[1. 2. 3.]


In [3]:
x=(1,2,3)
a=np.asarray(x)
print(a)

[1 2 3]


In [4]:
# Create Matrix in NumPy
matrix1= np.array([[1,3],
                   [5,7]])
print('2x2 matrix:\n',matrix1)

2x2 matrix:
 [[1 3]
 [5 7]]


In [5]:
matrix2= np.array([[2,3,5],[7,14,21],[1,3,5]])
print('\n3x3 matrix:\n',matrix2)


3x3 matrix:
 [[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]


In [8]:
a=np.array([[2,3,5],[7,14,21],[1,3,5]])
print(a)
print()
b=np.array([[2,3,5],[7,14,21],[1,3,5]])
print(b)
print()
c=a+b
print(c)

[[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]

[[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]

[[ 4  6 10]
 [14 28 42]
 [ 2  6 10]]


In [2]:
# Matrix multiplication --- we use the np.dot() function
# the no of columns of first matrix and the no of rows of second matrix should be equal.
import numpy as np

In [4]:
m1=np.array([[1,3],[5,7]])
m2=np.array([[2,6],[4,8]])
result=np.dot(m1,m2)
print('first matrix: \n',m1) 
print('second matrix: \n',m2)
print('m1xm2: \n',result)

first matrix: 
 [[1 3]
 [5 7]]
second matrix: 
 [[2 6]
 [4 8]]
m1xm2: 
 [[14 30]
 [38 86]]


In [5]:
# transpose of matrix --- np.transpose()
matrix1=np.array([[1,3],[5,7]])
print(matrix1)
print()
result=np.transpose(matrix1)
print(result)

[[1 3]
 [5 7]]

[[1 5]
 [3 7]]


In [6]:
# concatenation of two matrices or arrays
# horizontally stack numpy arrays using numpy.hstack()

x=np.array((3,5,7))
print(x)
print()
y=np.array((5,7,9))
print(y)
print()
print(np.hstack((x,y)))

[3 5 7]

[5 7 9]

[3 5 7 5 7 9]


In [7]:
x=np.array([[3],[5],[7]])
print(x)
print()
y=np.array([[5],[7],[9]])
print(y)
print()
print(np.hstack((x,y)))

[[3]
 [5]
 [7]]

[[5]
 [7]
 [9]]

[[3 5]
 [5 7]
 [7 9]]


In [8]:
# vertically stack numpy arrays using numpy.vstack()

x=np.array((3,5,7))
print(x)
print()
y=np.array((5,7,9))
print(y)
print()
print(np.vstack((x,y)))

[3 5 7]

[5 7 9]

[[3 5 7]
 [5 7 9]]


In [9]:
x=np.array([[3],[5],[7]])
print(x)
print()
y=np.array([[5],[7],[9]])
print(y)
print()
print(np.vstack((x,y)))

[[3]
 [5]
 [7]]

[[5]
 [7]
 [9]]

[[3]
 [5]
 [7]
 [5]
 [7]
 [9]]


In [10]:
# np.arange --- this function returns an ndarray object containing evenly spaced values within a given range

a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [11]:
a.ndim

1

In [12]:
x=np.arange(5,dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [14]:
x=np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [17]:
# numpy.linspace() --- It is similar to arange() function just that instead of step size, the number of evenly spaced values between the interval is specified.

import numpy as np
x=np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [18]:
x=np.linspace(10,20,5,endpoint=False)
print(x)

[10. 12. 14. 16. 18.]


In [19]:
# find retstep
x=np.linspace(10,20,5,retstep=True)
print(x)

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)


In [20]:
a=np.array([[3,3,2],[6,9,4],[5,5,8]])
print(a)

[[3 3 2]
 [6 9 4]
 [5 5 8]]


In [21]:
a.ndim

2

In [22]:
a.shape

(3, 3)

In [23]:
np.sum(a)

45

In [24]:
np.sum(a,axis=0) # sum of columns

array([14, 17, 14])

In [25]:
np.sum(a,axis=1) # sum of rows

array([ 8, 19, 18])

In [26]:
np.min(a)

2

In [27]:
np.max(a)

9

In [28]:
np.min(a,axis=1)

array([2, 4, 5])

In [29]:
np.max(a,axis=1)

array([3, 9, 8])

In [30]:
np.min(a,axis=0)

array([3, 3, 2])

In [31]:
np.max(a,axis=0)

array([6, 9, 8])

Shallow and Deep copy
-

In [2]:
l=[1,'2',3,4,5]
l1=l
l1

[1, '2', 3, 4, 5]

In [3]:
l1[2]=100
l1

[1, '2', 100, 4, 5]

In [4]:
l

[1, '2', 100, 4, 5]

In [6]:
l=[1,2,3,4,5]
l2=l.copy()
l2[1]=100
l2

[1, 100, 3, 4, 5]

In [7]:
l

[1, 2, 3, 4, 5]

In [8]:
print(id(l),id(l2))

2536123797056 2536124707328


In [9]:
# when does shallow copy fail --- nested structure

l=[[1,2,3],[4,56]]
l

[[1, 2, 3], [4, 56]]

In [10]:
l2=l.copy()
l2

[[1, 2, 3], [4, 56]]

In [11]:
l2[0][2]=100
l2

[[1, 2, 100], [4, 56]]

In [13]:
l # original list is not passed here 

[[1, 2, 100], [4, 56]]

In [14]:
import copy 

In [15]:
l=[[1,2,3],[4,5,6]]
l

[[1, 2, 3], [4, 5, 6]]

In [16]:
l2=copy.deepcopy(l)
l2

[[1, 2, 3], [4, 5, 6]]

In [17]:
l2[0][2]=100
l2

[[1, 2, 100], [4, 5, 6]]

In [18]:
l

[[1, 2, 3], [4, 5, 6]]

Random Number Generation
-
Generate Random Integer in NumPy
As discussed earlier, we use the random module to work with random numbers in NumPy.

In [19]:
import numpy as np

In [22]:
# generate random integer from 0 to 9
random_number = np.random.randint(0, 10)
print(random_number)


6


In [23]:
random_number = np.random.randint(0, 10)
print(random_number)

4


In [25]:
from numpy import random
random_number = random.randint(0,10)
print(random_number)

6


In [26]:
#Generate Random Float in NumPy
#We can also generate a random floating-point number between 0 and 1. 
#For that we use the random.rand() function. 

random_no=np.random.rand()
print(random_no)

0.1824780021424679


In [27]:
integer_array= np.random.randint(0,10,5)
print('1D random integer array:\n',integer_array)

1D random integer array:
 [0 8 0 6 8]


In [28]:
integer_array= np.random.randint(0,10,5)
print('1D random integer array:\n',integer_array)

1D random integer array:
 [2 3 5 1 1]


In [30]:
float_array= np.random.rand(5)
print('1D random float array:\n',float_array)

1D random float array:
 [0.91312844 0.42637388 0.87270552 0.18271516 0.89167014]


In [31]:
m1=np.random.randint(0,10,(3,4))
print('\n2D random integer array:\n',m1)


2D random integer array:
 [[7 8 2 3]
 [6 4 7 2]
 [1 5 0 7]]


In [32]:
m2=np.random.randint(0,10,(2,3))
print('\n2D random integer array:\n',m2)


2D random integer array:
 [[4 7 5]
 [9 9 7]]


In [33]:
a1=np.array([1,2,3,4,5])
# choose a random number from a1
random_choice = np.random.choice(a1)
print(random_choice)

3


In [35]:
# Numbers from Normal distribution with zero mean and standard deviation 1 --- randn

np.random.randn(5,5)

array([[ 0.21467815,  2.33045788, -0.46686996,  0.91042493,  0.66311616],
       [ 0.02598894,  1.57169675,  0.69012073,  1.3365655 , -0.82479952],
       [ 0.02449048, -1.05926941, -0.03207397,  0.43823369,  1.24517091],
       [ 1.14619019,  2.41613656,  0.03389213,  0.02537008, -0.94057901],
       [-0.2352007 , -1.11263845,  0.43626911,  1.68888852,  1.86582867]])

In [38]:
import numpy as np
from numpy.random import randint as ri

In [39]:
np.random.seed(675)
ri(1,100,(5,6))

array([[42, 81,  3, 10, 39, 37],
       [ 3, 57,  4, 90, 28, 41],
       [17, 61, 53, 98, 53, 16],
       [85, 95, 61, 83, 63, 11],
       [82, 82, 55, 34, 13, 99]])

In [40]:
np.random.seed(675)
M=ri(1,100,25).reshape(5,5)
M

array([[42, 81,  3, 10, 39],
       [37,  3, 57,  4, 90],
       [28, 41, 17, 61, 53],
       [98, 53, 16, 85, 95],
       [61, 83, 63, 11, 82]])

In [41]:
np.sort(M)

array([[ 3, 10, 39, 42, 81],
       [ 3,  4, 37, 57, 90],
       [17, 28, 41, 53, 61],
       [16, 53, 85, 95, 98],
       [11, 61, 63, 82, 83]])

In [42]:
np.sort(M,axis=0)

array([[28,  3,  3,  4, 39],
       [37, 41, 16, 10, 53],
       [42, 53, 17, 11, 82],
       [61, 81, 57, 61, 90],
       [98, 83, 63, 85, 95]])

In [46]:
a=ri(1,100,30)
b=a.reshape(6,5)
b

array([[82, 55, 34, 13, 99],
       [90, 78, 64, 12, 40],
       [40, 33, 62, 91, 42],
       [95, 72, 47, 77, 39],
       [73, 46, 62, 38, 77],
       [39, 69, 84, 71,  8]])

In [47]:
a

array([82, 55, 34, 13, 99, 90, 78, 64, 12, 40, 40, 33, 62, 91, 42, 95, 72,
       47, 77, 39, 73, 46, 62, 38, 77, 39, 69, 84, 71,  8])

In [48]:
a.max()

99

In [49]:
a.min()

8

In [51]:
a.argmax() # returns the index of the maximum element

4

In [52]:
ls=[121,23,34,145,56,18]
a=np.array(ls)
a.argsort()

array([5, 1, 2, 4, 0, 3], dtype=int64)

In [53]:
b.max()

99

In [54]:
b.argmax()

4

In [55]:
b.argmax(axis=1)

array([4, 0, 3, 0, 4, 2], dtype=int64)

In [64]:
# Conditional Selection
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [57]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [58]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
a[a<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [61]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [62]:
a[a==5]

array([5])

In [63]:
a[a%2!=0]=0
a

array([ 0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16,  0,
       18,  0, 20])

Where Function
-

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,2])
a

array([1, 2, 3, 4, 5, 2])

In [3]:
a.ndim

1

In [4]:
a.shape

(6,)

In [5]:
x=np.where(a==2)
x

(array([1, 5], dtype=int64),)

In [6]:
y=np.where(a==3)
y

(array([2], dtype=int64),)

In [7]:
b=np.array([1,2,3,4,5,6])
b

array([1, 2, 3, 4, 5, 6])

In [9]:
np.where(b<4)

(array([0, 1, 2], dtype=int64),)

In [10]:
np.where(b>5)

(array([5], dtype=int64),)

In [11]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.where(x%2==0)

(array([1, 3, 5, 7, 9], dtype=int64),)

In [13]:
np.where(x%2!=0)

(array([0, 2, 4, 6, 8], dtype=int64),)

In [14]:
# searchsorted

x=np.array([1,2,3,4,10,11,15])
x

array([ 1,  2,  3,  4, 10, 11, 15])

In [15]:
np.searchsorted(x,8)

4

In [16]:
np.searchsorted(x,12)

6

Indexing and Slicing
-

In [17]:
x=np.array([[1,2,3,9,10],[12,34,4,5,6],[65,76,7,8,9],[12,34,4,5,6],[65,76,7,8,9]])
print(x)

[[ 1  2  3  9 10]
 [12 34  4  5  6]
 [65 76  7  8  9]
 [12 34  4  5  6]
 [65 76  7  8  9]]


In [19]:
x[1:3,1:3]

array([[34,  4],
       [76,  7]])

In [20]:
x[2:4,2:4]

array([[7, 8],
       [4, 5]])

In [24]:
x[3:,1:3]

array([[34,  4],
       [76,  7]])

Comparision between list and array
-
three benefits of array - 

1.Takes less memory
2. fast
3. convinient

In [25]:
import sys
import time

sys.getsizeof(100)

28

In [26]:
l=range(200000)
print(sys.getsizeof(2)*len(l))

5600000


In [27]:
a=np.arange(200000)
print(a.itemsize)
print()
print(a.itemsize*len(a))

4

800000


In [29]:
a1=range(1000000)
b1=range(1000000)
start=time.time() # start time 
c1=[(x+y) for x,y in zip(a1,b1)]
print('time taken: ',(time.time()-start)*1000) # end time-start

time taken:  281.278133392334


In [30]:
a2=np.arange(1000000)
b2=np.arange(1000000)
start=time.time()
c2=a2+b2
print('time taken by array: ',(time.time()-start)*1000)

time taken by array:  7.994651794433594


In [31]:
n1=np.arange(100)
n2=np.arange(100)
n1*n2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [32]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [33]:
a.shape

(24,)

In [35]:
b=a.reshape(2,4,3)
b
#b.ravel()

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [37]:
b.ravel()  #converts to 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [38]:
a.itemsize # returns the length of each element of array in bytes

4

In [39]:
a=np.array([1.,2,3,4])
a.itemsize

8

In [42]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print()
print(b)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [45]:
np.concatenate((a,b),axis=0) # vstack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [46]:
np.concatenate((a,b),axis=1) # hstack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [47]:
a=np.arange(12)
np.split(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [48]:
np.split(a,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [49]:
a=np.array([[1,2,3],[4,5,6]])
np.append(a,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a=np.array([[1,2,3],[4,5,6]])
np.append(a,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])